### ISSUE TITLE
How to make it executable?

### ISSUE THREAD

**Issue by DestoGit** [tienanh306201z/alarm_and_clock_windows_clone#1]
Hi,
Do you know how to make it an .exe executable?
Thanks.

**Comment by tienanh306201z** [comment]
This code is just include debug code only I built for my school project! You can clone it to your IDE and build it in release mode to get .exe executable file!
Good luck.

**Comment by DestoGit** [comment]
Ok, thanks for the directions and great app. I'm not a C# coder. 
I found those other ones with the .exe provided but yours seems best:
https://github.com/estorgio/alarm
https://github.com/TeenageMutantCoder/Alarm-Clock/releases/tag/v1.0
I'll look around on how to build it in release mode.
But might be profitable for other users having the .exe direclty downloadable for testing first without IDE.
Thanks again.
Be well!

**Comment by DestoGit** [comment]
All right, I could find the solution from this post:

_In the bin\Release (or bin\Debug) folder, the .exe will be in there._
https://stackoverflow.com/a/2962853/10789707

Thankfully (I don't have Visual Studio setup on my end) we don't need to build it again as you provided/complied the .exe already in this folder:
C:\Users\YOURUSERNAME\Desktop\alarm_and_clock_windows_clone-1.0\Alarm and Clock App\bin\Debug

Alarm_and_Clock_App.exe

I just copied it to the desktop.

I'll test it next. Thanks again!

**Comment by DestoGit** [comment]
Had this error I could fix by installing the Century Gothic font:

https://i.imgur.com/EueX4lZ.png

https://freefontsdownload.net/free-century-gothic-font-32089.htm

**Comment by DestoGit** [comment]
The timer raises this error:
https://i.imgur.com/uHXfUq6.png

I found out we need to build it in a release folder from this answer's 2nd comment:
https://stackoverflow.com/a/12889281/10789707

There's no release folder under the bin folder in your shared code, only the debug folder.


Can you please provide the compiled version if it's a matter of seconds for you to build it in your system? 
I'd be grateful as I don't have Visual Studio or VSCode nor PyCharm installed and I'm not familiar on how the process works with other IDEs.

Thanks in advance.

**Comment by DestoGit** [comment]
I could build the release exe following this tutorial:
https://www.youtube.com/watch?v=iFsLvNO4HKY

There need custom .wav files to fix errors:
https://i.imgur.com/EZX94XT.png

**Comment by tienanh306201z** [comment]
> I could build the release exe following this tutorial: https://www.youtube.com/watch?v=iFsLvNO4HKY
> 
> There need custom .wav files to fix errors: https://i.imgur.com/EZX94XT.png

sorry for the inconvenience! I built this project almost 3 years ago on my Windows device. But now I change to use Mac for my work purposes. So it's not possible for me to figure this project out on MacOS. Hope that you can find any solution!

Good luck!

**Comment by tienanh306201z** [comment]
> All right, I could find the solution from this post:
> 
> _In the bin\Release (or bin\Debug) folder, the .exe will be in there._ https://stackoverflow.com/a/2962853/10789707
> 
> Thankfully (I don't have Visual Studio setup on my end) we don't need to build it again as you provided/complied the .exe already in this folder: C:\Users\YOURUSERNAME\Desktop\alarm_and_clock_windows_clone-1.0\Alarm and Clock App\bin\Debug
> 
> Alarm_and_Clock_App.exe
> 
> I just copied it to the desktop.
> 
> I'll test it next. Thanks again!

All the element in this project is built based on Windows Form framework from Microsoft. And you can definitely run it on PyCharm IDE with free student package supported by Jetbrains (it's pretty easy to get). Remember to install some required tools from Windows Form instructions.
